import { Str, Bool, DateTime, Num } from "chanfana";
import type { Context } from "hono";
import { z } from "zod";

// Use the global Env interface generated by wrangler types
// See: worker-configuration.d.ts
export type AppContext = Context<{ Bindings: Env }>;

// Email check response
export const EmailCheckResponse = z.object({
	email: Str({ example: "user@tempmail.com" }),
	domain: Str({ example: "tempmail.com" }),
	is_disposable: Bool({ example: true }),
	is_valid_format: Bool({ example: true }),
	checked_at: DateTime(),
	reacher: z.object({
		is_reachable: Str({ example: "safe" }),
		misc: z.object({
			is_disposable: Bool({ example: true }),
			is_role_account: Bool({ example: false }),
		}),
		mx: z.object({
			accepts_mail: Bool({ example: true }),
			records: z.array(Str()),
		}),
		smtp: z.object({
			can_connect_smtp: Bool({ example: true }),
			has_full_inbox: Bool({ example: false }),
			is_catch_all: Bool({ example: false }),
			is_deliverable: Bool({ example: true }),
			is_disabled: Bool({ example: false }),
		}),
		syntax: z.object({
			is_valid_syntax: Bool({ example: true }),
			username: Str({ example: "user" }),
			domain: Str({ example: "tempmail.com" }),
		}),
	}).optional(),
});

// API key creation request
export const CreateKeyRequest = z.object({
	email: Str({ example: "developer@company.com" }),
	turnstileToken: Str({ example: "XXXX.YYYY.ZZZZ" }).optional(),
});

// API key creation response
export const CreateKeyResponse = z.object({
	success: Bool(),
	message: Str({ example: "API key sent to your email" }),
});

// API key info response
export const KeyInfoResponse = z.object({
	exists: Bool(),
	requests_today: Num({ example: 42 }),
	daily_limit: Num({ example: 1000 }),
	created_at: DateTime(),
});

// Error response
export const ErrorResponse = z.object({
	error: Str({ example: "Invalid email format" }),
	code: Str({ example: "INVALID_EMAIL" }),
});

// Stats response
export const StatsResponse = z.object({
	total_emails_checked: Num({ example: 1247893 }),
	total_disposable_domains: Num({ example: 4521 }),
	community_reports: Num({ example: 23 }),
});

// ==================== ADMIN API SCHEMAS ====================

// Admin account info response
export const AdminAccountResponse = z.object({
	email: Str({ example: "developer@company.com" }),
	created_at: DateTime(),
	total_usage: Num({ example: 15234 }),
	requests_today: Num({ example: 42 }),
	daily_limit: Num({ example: 1000 }),
	custom_daily_limit: Num({ example: 5000 }).optional(),
});

// Admin account list response with pagination
export const AdminAccountListResponse = z.object({
	accounts: z.array(AdminAccountResponse),
	total_count: Num({ example: 150 }),
	limit: Num({ example: 100 }),
	offset: Num({ example: 0 }),
});

// Update limit request
export const UpdateLimitRequest = z.object({
	daily_limit: Num({
		description: "New daily usage limit (0 to 1,000,000)",
		example: 5000
	}).min(0).max(1000000),
});

// Update limit response
export const UpdateLimitResponse = z.object({
	success: Bool(),
	previous_limit: Num({ example: 1000 }),
	new_limit: Num({ example: 5000 }),
});

// Unauthorized error response
export const UnauthorizedResponse = z.object({
	error: Str({ example: "Unauthorized" }),
	code: Str({ example: "UNAUTHORIZED" }),
});

