import { Str, Bool, DateTime, Num } from "chanfana";
import type { Context } from "hono";
import { z } from "zod";

// Use the global Env interface generated by wrangler types
// See: worker-configuration.d.ts
export type AppContext = Context<{ Bindings: Env }>;

// Email check response
export const EmailCheckResponse = z.object({
	email: Str({ example: "user@tempmail.com" }),
	domain: Str({ example: "tempmail.com" }),
	is_disposable: Bool({ example: true }),
	is_valid_format: Bool({ example: true }),
	checked_at: DateTime(),
});

// API key creation request
export const CreateKeyRequest = z.object({
	email: Str({ example: "developer@company.com" }),
	turnstileToken: Str({ example: "XXXX.YYYY.ZZZZ" }).optional(),
});

// API key creation response
export const CreateKeyResponse = z.object({
	success: Bool(),
	message: Str({ example: "API key sent to your email" }),
});

// API key info response
export const KeyInfoResponse = z.object({
	exists: Bool(),
	requests_today: Num({ example: 42 }),
	daily_limit: Num({ example: 1000 }),
	created_at: DateTime(),
});

// Error response
export const ErrorResponse = z.object({
	error: Str({ example: "Invalid email format" }),
	code: Str({ example: "INVALID_EMAIL" }),
});

